Repository 2024-Winter-Bootcamp-Team-A/frontend, pull requests merged in 2025-01, with the labels that each got.

#2 [feat] test
  README.md
Labels: help wanted

#5 [design] 테스트
  README.md
Labels: good first issue

#13 [design] 빌드환경구축, 사이드패널 와이어프레임
  .husky/pre-commit
  pages/content-ui/src/App.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/index.tsx
  pnpm-lock.yaml
Labels: 디자인/퍼블리싱

#17 [design] newtab에 faq 추가
  .husky/pre-commit
  pages/new-tab/src/FAQModal.tsx
  pages/new-tab/src/FAQModal_NoQ.tsx
  pages/new-tab/src/NewTab.tsx
Labels: 디자인/퍼블리싱

#22 [design] search 화면 구현
  pages/new-tab/src/components/FAQModal.tsx
  pages/new-tab/src/components/FAQModal_NoQ.tsx
  pages/new-tab/src/components/Search.tsx
  pnpm-lock.yaml
Labels: 디자인/퍼블리싱

#27 [design] stats 화면 구현
  pages/new-tab/src/NewTab.tsx
  pages/new-tab/src/components/Stats.tsx
Labels: 디자인/퍼블리싱

#28 [design]사이드패널
  package-lock.json
  pages/side-panel/src/SidePanel_short.css
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/comment.tsx
  pages/side-panel/src/index.tsx
  pages/side-panel/src/request_short.tsx
Labels: 디자인/퍼블리싱

#24 [design] 오늘의 쇼츠
  .husky/pre-commit
  pages/new-tab/package.json
  pages/new-tab/public/images/소년이온다표지.png
  pages/new-tab/public/images/채식주의자표지.png
  pages/new-tab/public/리롤버튼.svg
  pages/new-tab/public/오른쪽문장배경.png
  pages/new-tab/public/왼쪽문장배경.png
  pages/new-tab/src/MainTodayShorts.css
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/NewTab.tsx
  pages/new-tab/src/components/BookCard.css
  pages/new-tab/src/components/BookCard.tsx
  pages/new-tab/src/components/MainNav.tsx
  pages/new-tab/src/components/ShortsPlayer.tsx
  pages/new-tab/src/index.tsx
  pages/new-tab/tailwind.config.ts
  pnpm-lock.yaml
Labels: 디자인/퍼블리싱

#30 design : 지우님 패널 수정
  pages/new-tab/src/components/Stats.tsx
  pages/new-tab/src/index.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/index.tsx
Labels: 디자인/퍼블리싱

#33 [feat] 서치연결
  pages/new-tab/src/components/MainNav.tsx
  pages/new-tab/src/components/Search.tsx
  pages/new-tab/src/index.tsx
Labels: 기능구현

#35 [design] 통계화면 수정
  pages/new-tab/src/components/Stats.tsx
Labels: 디자인/퍼블리싱

#40 [feat] 서치 연동
  pages/new-tab/src/components/MainNav.tsx
  pages/new-tab/src/components/Search.tsx
Labels: 기능구현

#47 [Design] 카드플립 구현 완료
  pages/new-tab/public/nowish.svg
  pages/new-tab/src/components/ShortsModal.tsx
Labels: 디자인/퍼블리싱

#52 design/#52 오늘의 쇼츠 반응형 및 쇼츠 보러가기 모달창, 카드저장 alert
  pages/new-tab/src/MainTodayShorts.css
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/components/BookCard.css
  pages/new-tab/src/components/BookCard.tsx
  pages/new-tab/tailwind.config.ts
Labels: 디자인/퍼블리싱

#54 [design] 메인페이지, 마이페이지 수정
  pages/new-tab/public/person.svg
  pages/new-tab/src/components/MainBoard.tsx
  pages/new-tab/src/components/MainBookcase.tsx
  pages/new-tab/src/components/MyPage.tsx
Labels: 디자인/퍼블리싱

#53 [Design] 사이드패널 구현 최종. . .
  pages/side-panel/public/comment.svg
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/comment.tsx
  pages/side-panel/src/index.tsx
Labels: 디자인/퍼블리싱

#57 [design] : 사이드패널 세부설정
  pages/side-panel/src/SideLogin.tsx
  pages/side-panel/src/SidePanel.tsx
  pages/side-panel/src/SidePanelShorts.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/SideSignUp.tsx
  pages/side-panel/src/components/SideButton.tsx
  pages/side-panel/src/components/SideInput.tsx
  pages/side-panel/src/components/SideNav.tsx
  pages/side-panel/src/index.tsx
Labels: 디자인/퍼블리싱

#63 [feat] 마이페이지 api 연동
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/components/MyPage.tsx
Labels: 기능구현

#67 [design] 전광판, 화살표 변경
  pages/new-tab/index.html
  pages/new-tab/public/길거리 배경.png
  pages/new-tab/public/오른쪽화살표.svg
  pages/new-tab/public/왼쪽화살표.svg
  pages/new-tab/src/components/MainBoard.tsx
  pages/new-tab/src/components/MainBookcase.tsx
  pages/new-tab/src/components/Stats.tsx
  pages/new-tab/src/index.css
  pages/new-tab/tailwind.config.ts
Labels: 디자인/퍼블리싱

#70 [Feat] 사이드패널 회원가입,로그인 유저정보 토큰 수신
  pages/new-tab/src/NewTab.tsx
  pages/new-tab/src/components/MainBookcase.tsx
  pages/new-tab/src/components/ShortsModal.tsx
  pages/side-panel/public/nowish.svg
  pages/side-panel/src/API/login.ts
  pages/side-panel/src/SideLogin.tsx
  pages/side-panel/src/SidePanel.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/SideSignUp.tsx
  pages/side-panel/src/components/SideInput.tsx
Labels: 기능구현

#72 Feat/#69 사이드패널 api 연동
  pages/side-panel/src/API/AddComment.ts
  pages/side-panel/src/API/HandleShare.ts
  pages/side-panel/src/SideLogin.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/SideSignUp.tsx
  pages/side-panel/src/index.tsx
  pages/side-panel/src/request_short.tsx
Labels: 기능구현

#74 [Feat] 쇼츠모달 댓글api 연동
  pages/new-tab/src/components/CommentModal.tsx
  pages/new-tab/src/components/MainBookcase.tsx
  pages/new-tab/src/components/ShortsModal.tsx
  pages/side-panel/src/SideLogin.tsx
Labels: 기능구현

#77 [feat] 마이페이지 서치 api 연결
  pages/new-tab/src/components/MainNav.tsx
  pages/new-tab/src/components/MyPage.tsx
  pages/new-tab/src/components/Search.tsx
  pages/new-tab/src/components/SentenceCardModal.tsx
  pages/new-tab/src/components/WatchedModal.tsx
  pages/new-tab/src/components/WishedModal.tsx
Labels: 기능구현

#78 Feat/#73 오늘의 숏츠 및 stat 페이지 api 연동
  pages/new-tab/package.json
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/components/ShortsModal.tsx
  pages/new-tab/src/components/Stats.tsx
  pages/new-tab/src/components/StatsBar.tsx
  pages/new-tab/src/components/StatsData.tsx
  pages/new-tab/src/components/StatsPie.tsx
  pages/new-tab/src/components/StatsStacked.tsx
  pages/new-tab/src/components/ui/chart.tsx
  pages/new-tab/src/index.css
  pnpm-lock.yaml
Labels: 기능구현

#83 [feat] 쇼츠 모달 오류 수정
  pages/new-tab/src/components/ShortsModal.tsx
Labels: 기능구현

#86 Feat/#85
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/components/Stats.tsx
  pages/new-tab/src/components/StatsBar.tsx
  pages/new-tab/src/components/StatsPie.tsx
  pages/side-panel/public/nowish.svg
  pages/side-panel/src/API/AddWished.ts
  pages/side-panel/src/API/DeleteWished.ts
  pages/side-panel/src/API/HandleShare.ts
  pages/side-panel/src/API/MakeShorts.ts
  pages/side-panel/src/SidePanel.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/request_short.tsx
Labels: 기능구현

#87 [design]오늘의 쇼츠 디테일, 서치 모달창 연결
  pages/new-tab/public/6.mp4
  pages/new-tab/src/MainTodayShorts.css
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/components/Search.tsx
Labels: 디자인/퍼블리싱

#89 [feat] 메인페이지 api 연동 완료
  pages/new-tab/public/hangang.mp4
  pages/new-tab/public/nowish.svg
  pages/new-tab/src/NewTab.tsx
  pages/new-tab/src/components/MainBoard.tsx
  pages/new-tab/src/components/MainBookcase.tsx
  pages/new-tab/src/components/ShortsModal.tsx
Labels: 기능구현

#92 [design] 헤더바, 통계 화살표 수정
  pages/new-tab/src/components/MainNav.tsx
  pages/new-tab/src/components/MyPage.tsx
  pages/new-tab/src/components/Stats.tsx
Labels: 디자인/퍼블리싱

#94 [design] 통계 글씨, 오늘의 쇼츠 라운드
  pages/new-tab/src/MainTodayShorts.tsx
  pages/new-tab/src/components/Stats.tsx
Labels: 디자인/퍼블리싱

#97 design : 사이드패널 베스트숏츠, 라우팅버튼 라운드 고침
  pages/new-tab/src/components/MainBoard.tsx
  pages/side-panel/src/SideLogin.tsx
  pages/side-panel/src/SidePanel.css
  pages/side-panel/src/SidePanel.tsx
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/SideSignUp.tsx
  pages/side-panel/src/components/SideButton.tsx
  pages/side-panel/src/request_short.tsx
Labels: 디자인/퍼블리싱

#98 [design] 메인페이지 수정
  pages/new-tab/public/길거리배경1.png
  pages/new-tab/src/components/MainBoard.tsx
  pages/new-tab/src/components/MainBookcase.tsx
Labels: 디자인/퍼블리싱

#100 [design] 쇼츠 모달창 수정
  pages/new-tab/src/components/ShortsModal.tsx
Labels: 디자인/퍼블리싱

#102 [design] 숏츠 만들기 사이드 패널 수정
  pages/side-panel/src/request_short.tsx
Labels: 디자인/퍼블리싱

#104 design : 아이콘 적용 및 배경 사이드패널 투명도 설정
  pages/new-tab/public/북클립글자.png
  pages/new-tab/src/components/MainNav.tsx
  pages/side-panel/public/북클립글자.png
  pages/side-panel/src/SideLogin.tsx
  pages/side-panel/src/SidePanel.tsx
  pages/side-panel/src/SidePanel_short.css
  pages/side-panel/src/SidePanel_short.tsx
  pages/side-panel/src/SideSignUp.tsx
  pages/side-panel/src/request_short.tsx
Labels: 디자인/퍼블리싱

#105 [Design] 로딩창 구현
  pages/side-panel/public/loading.gif
  pages/side-panel/src/LoadingModal.tsx
  pages/side-panel/src/request_short.tsx
Labels: 디자인/퍼블리싱

#107 [feat] 로직 수정완료
  pages/side-panel/src/request_short.tsx
Labels: 기능구현
